import Head from 'next/head';

function Home() {
    return (
        <div>
            <Head>
                <title>Home Next App</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <header>
                <nav className='flex'>
                    <ul>
                        <li>
                            <a href='/'>Home</a>
                        </li>
                        <li>
                            <a href='/about'>About</a>
                        </li>
                        <li>
                            <a href='/contact'>Contact</a>
                        </li>
                    </ul>
                </nav>
            </header>
            <main>
                test
            </main>

            <footer>
                Footer
            </footer>
        </div>
    );
}

export default Home;
